In [17]:
import torch 
import torch.nn as nn
import numpy as np
import math


loss_f = nn.CrossEntropyLoss(weight=None, reduction='none')
# 生成网络输出 以及 目标输出
output = torch.ones(2, 3, requires_grad=True) * 0.5      # 假设一个三分类任务，batchsize=2，假设每个神经元输出都为0.5
target = torch.from_numpy(np.array([0, 1])).type(torch.LongTensor)

print('output: \n', output)
print('target: \n', target)

loss = loss_f(output, target)

loss


output: 
 tensor([[0.5000, 0.5000, 0.5000],
        [0.5000, 0.5000, 0.5000]], grad_fn=<MulBackward0>)
target: 
 tensor([0, 1])


tensor([1.0986, 1.0986], grad_fn=<NllLossBackward>)

In [18]:
# 熟悉计算公式，手动计算第一个样本
output = output[0].detach().numpy()
output_1 = output[0]              # 第一个样本的输出值
target_1 = target[0].numpy()

# 第一项
x_class = output[target_1]
# 第二项
exp = math.e
sigma_exp_x = pow(exp, output[0]) + pow(exp, output[1]) + pow(exp, output[2])
log_sigma_exp_x = math.log(sigma_exp_x)
# 两项相加
loss_1 = -x_class + log_sigma_exp_x
print('---------------------------------------------------  手动计算')
print('第一个样本的loss: ', loss_1)

---------------------------------------------------  手动计算
第一个样本的loss:  1.0986122886681098


In [19]:
# 各类别权重
weight = torch.from_numpy(np.array([0.6, 0.2, 0.2])).float()

# 生成网络输出 以及 目标输出
output = torch.from_numpy(np.array([[0.7, 0.2, 0.1], [0.4, 1.2, 0.4]])).float()  
output.requires_grad = True
target = torch.from_numpy(np.array([0, 0])).type(torch.LongTensor)


loss_f = nn.NLLLoss(weight=weight, size_average=True, reduce=False)
loss = loss_f(output, target)

print('\nloss: \n', loss)
print('\n第一个样本是0类，loss = -(0.6*0.7)={}'.format(loss[0]))
print('\n第二个样本是0类，loss = -(0.6*0.4)={}'.format(loss[1]))


loss: 
 tensor([-0.4200, -0.2400], grad_fn=<NllLossBackward>)

第一个样本是0类，loss = -(0.6*0.7)=-0.42000001668930054

第二个样本是0类，loss = -(0.6*0.4)=-0.24000000953674316
