In [3]:
import torch
X = torch.Tensor([22, 5, 6, 8, 10, 19, 2])

X_max = X.max()
X_min = X.min()

numerator = X - X_min
denominator = X_max - X_min

X_new = numerator / denominator

print("X_max: ", X_max)
print("X_min: ", X_min)
print("numerator: ", numerator)
print("denominator: ", denominator)
print("X_new: ", X_new)

X_max:  tensor(22.)
X_min:  tensor(2.)
numerator:  tensor([20.,  3.,  4.,  6.,  8., 17.,  0.])
denominator:  tensor(20.)
X_new:  tensor([1.0000, 0.1500, 0.2000, 0.3000, 0.4000, 0.8500, 0.0000])


In [7]:
import torch
X = torch.Tensor([22, 5, 6, 8, 10, 19, 2])
n = len(X)

mean = X.sum() / n

std = (((X-mean)**2).sum()/n).sqrt() # X.std(unbiased=False)
z_scores = (X - mean) / std

denominator = X_max - X_min


print(mean, std, z_scores, sep="\n")


tensor(10.2857)
tensor(6.9016)
tensor([ 1.6973, -0.7659, -0.6210, -0.3312, -0.0414,  1.2626, -1.2005])


In [8]:
# Input Tensor: 4 matrices of 5 rows and 3 columns
X = torch.randint(0, 100, (4, 5, 3)).float()

# Shape to be Normalized: 5 rows, 3 columns
normalized_shape = (5, 3)

# Number of Dimensions in the Shape to be Normalized
D = len(normalized_shape)

# Set the Default Values for Epsilon, Gamma, and Beta
eps = 1e-5
gamma = torch.ones(normalized_shape)
beta = torch.zeros(normalized_shape)

X

tensor([[[15., 88., 64.],
         [21., 28., 21.],
         [22., 27., 88.],
         [92., 61., 25.],
         [45.,  6., 61.]],

        [[80., 99.,  4.],
         [73., 82., 88.],
         [61., 83., 31.],
         [51., 46., 76.],
         [78., 10., 59.]],

        [[88., 26., 88.],
         [52., 27., 63.],
         [36., 93., 34.],
         [17., 63.,  8.],
         [ 9., 27.,  1.]],

        [[13., 73., 16.],
         [50., 12., 86.],
         [ 1., 30., 28.],
         [14., 59.,  5.],
         [96., 41., 32.]]])

In [10]:
# Normalize
for i in range(0,4):               # loop through each matrix
  mean = X[i].mean()               # mean         
  var = X[i].var(unbiased=False)   # variance
  layer_norm = (X[i]-mean)/(torch.sqrt(var+eps))*gamma + beta 
  print("X[i]:\n", X[i])
  print(f"μ = {mean:.4f}")            
  print(f"σ^{2} = {var:.4f}") 
  print(layer_norm)
  print("="*50)

X[i]:
 tensor([[15., 88., 64.],
        [21., 28., 21.],
        [22., 27., 88.],
        [92., 61., 25.],
        [45.,  6., 61.]])
μ = 44.2667
σ^2 = 792.4622
tensor([[-1.0396,  1.5535,  0.7010],
        [-0.8265, -0.5778, -0.8265],
        [-0.7910, -0.6134,  1.5535],
        [ 1.6956,  0.5944, -0.6844],
        [ 0.0261, -1.3594,  0.5944]])
X[i]:
 tensor([[80., 99.,  4.],
        [73., 82., 88.],
        [61., 83., 31.],
        [51., 46., 76.],
        [78., 10., 59.]])
μ = 61.4000
σ^2 = 746.2400
tensor([[ 0.6809,  1.3764, -2.1012],
        [ 0.4246,  0.7541,  0.9737],
        [-0.0146,  0.7907, -1.1128],
        [-0.3807, -0.5637,  0.5345],
        [ 0.6077, -1.8816, -0.0879]])
X[i]:
 tensor([[88., 26., 88.],
        [52., 27., 63.],
        [36., 93., 34.],
        [17., 63.,  8.],
        [ 9., 27.,  1.]])
μ = 42.1333
σ^2 = 878.1155
tensor([[ 1.5478, -0.5444,  1.5478],
        [ 0.3330, -0.5107,  0.7042],
        [-0.2070,  1.7166, -0.2745],
        [-0.8482,  0.7042, -1.1519],


In [12]:
import torch.nn as nn

layer_normalization = nn.LayerNorm(normalized_shape) # nn.LayerNorm((5,3))
layer_normalization(X)

tensor([[[-1.0396,  1.5535,  0.7010],
         [-0.8265, -0.5778, -0.8265],
         [-0.7910, -0.6134,  1.5535],
         [ 1.6956,  0.5944, -0.6844],
         [ 0.0261, -1.3594,  0.5944]],

        [[ 0.6809,  1.3764, -2.1012],
         [ 0.4246,  0.7541,  0.9737],
         [-0.0146,  0.7907, -1.1128],
         [-0.3807, -0.5637,  0.5345],
         [ 0.6077, -1.8816, -0.0879]],

        [[ 1.5478, -0.5444,  1.5478],
         [ 0.3330, -0.5107,  0.7042],
         [-0.2070,  1.7166, -0.2745],
         [-0.8482,  0.7042, -1.1519],
         [-1.1181, -0.5107, -1.3881]],

        [[-0.8339,  1.2451, -0.7300],
         [ 0.4482, -0.8686,  1.6956],
         [-1.2497, -0.2449, -0.3142],
         [-0.7993,  0.7600, -1.1111],
         [ 2.0421,  0.1363, -0.1756]]], grad_fn=<NativeLayerNormBackward>)

In [21]:
X = torch.randint(0, 100, (2,3,5), dtype=torch.float32)

normalized_shape = (5,)

D = len(normalized_shape) # 1

layer_normalization = nn.LayerNorm(normalized_shape)

layer_normalization.state_dict()

OrderedDict([('weight', tensor([1., 1., 1., 1., 1.])),
             ('bias', tensor([0., 0., 0., 0., 0.]))])

In [22]:
X

tensor([[[83., 68., 94., 41., 10.],
         [70.,  5., 13., 97., 14.],
         [14., 27., 97., 91., 67.]],

        [[43., 86., 77.,  9., 51.],
         [91., 43., 66., 23.,  1.],
         [33., 19., 87., 67., 62.]]])

In [23]:
X.mean(2, keepdims=True) # maintains the dimensions of X

tensor([[[59.2000],
         [39.8000],
         [59.2000]],

        [[53.2000],
         [44.8000],
         [53.6000]]])

In [24]:
layer_normalization(X)

tensor([[[ 0.7841,  0.2899,  1.1465, -0.5996, -1.6209],
         [ 0.8202, -0.9451, -0.7279,  1.5535, -0.7007],
         [-1.3529, -0.9638,  1.1314,  0.9518,  0.2335]],

        [[-0.3747,  1.2050,  0.8743, -1.6238, -0.0808],
         [ 1.4638, -0.0570,  0.6717, -0.6907, -1.3877],
         [-0.8428, -1.4156,  1.3665,  0.5482,  0.3437]]],
       grad_fn=<NativeLayerNormBackward>)

In [26]:
class LayerNorm(nn.Module):
    def __init__(self, features, eps=1e-5):
        super().__init__()
        # 初始化 gamma 参数为全1
        self.gamma = nn.Parameter(torch.ones(features))
        # 初始化 beta 参数为全0
        self.beta = nn.Parameter(torch.zeros(features))
        # 初始化 epsilon
        self.eps = eps

    def forward(self, src):
        # 计算 token embeddings 的均值
        mean = src.mean(-1, keepdim=True)        
        # 计算 token embeddings 的方差
        var = src.var(-1, keepdim=True, unbiased=False)
        # 返回归一化后的值
        return self.gamma * (src - mean) / torch.sqrt(var + self.eps) + self.beta

In [30]:
layer_norm = LayerNorm(features=5)
layer_norm(X)

tensor([[[ 0.7841,  0.2899,  1.1465, -0.5996, -1.6209],
         [ 0.8202, -0.9451, -0.7279,  1.5535, -0.7007],
         [-1.3529, -0.9638,  1.1314,  0.9518,  0.2335]],

        [[-0.3747,  1.2050,  0.8743, -1.6238, -0.0808],
         [ 1.4638, -0.0570,  0.6717, -0.6907, -1.3877],
         [-0.8428, -1.4156,  1.3665,  0.5482,  0.3437]]],
       grad_fn=<AddBackward0>)